// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvYh4waquMAnUNxTdYrCm8YRpim6_-oP8',
    appId: '1:1088612340992:web:b40762314effc762d68fe5',
    messagingSenderId: '1088612340992',
    projectId: 'mobile-project-fitquest-aebdf',
    authDomain: 'mobile-project-fitquest-aebdf.firebaseapp.com',
    storageBucket: 'mobile-project-fitquest-aebdf.firebasestorage.app',
    measurementId: 'G-3EYY1FJZT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRvvS4osESFCPVQ3-wnJkECvwqP1vcs-g',
    appId: '1:1088612340992:android:b7a9bcf8e446c6a6d68fe5',
    messagingSenderId: '1088612340992',
    projectId: 'mobile-project-fitquest-aebdf',
    storageBucket: 'mobile-project-fitquest-aebdf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2IgC2vuRLUJPH0v9qnsnL7t1zjTChabI',
    appId: '1:1088612340992:ios:d4706dcf8d26bcfcd68fe5',
    messagingSenderId: '1088612340992',
    projectId: 'mobile-project-fitquest-aebdf',
    storageBucket: 'mobile-project-fitquest-aebdf.firebasestorage.app',
    iosBundleId: 'com.example.mobileProjectFitquest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2IgC2vuRLUJPH0v9qnsnL7t1zjTChabI',
    appId: '1:1088612340992:ios:d4706dcf8d26bcfcd68fe5',
    messagingSenderId: '1088612340992',
    projectId: 'mobile-project-fitquest-aebdf',
    storageBucket: 'mobile-project-fitquest-aebdf.firebasestorage.app',
    iosBundleId: 'com.example.mobileProjectFitquest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvYh4waquMAnUNxTdYrCm8YRpim6_-oP8',
    appId: '1:1088612340992:web:f1a80e03261870ddd68fe5',
    messagingSenderId: '1088612340992',
    projectId: 'mobile-project-fitquest-aebdf',
    authDomain: 'mobile-project-fitquest-aebdf.firebaseapp.com',
    storageBucket: 'mobile-project-fitquest-aebdf.firebasestorage.app',
    measurementId: 'G-C0LXYP4VL6',
  );

}